source: app
destination: web

title: Patricia Anne Ilano | Web Developer
description: >
     Web Developer from Manila
url: "https://ilanopat.github.io"
baseurl: ""
photo_url: "https://patriciailano.files.wordpress.com/2017/10/rnqpuaql_400x400.jpg?w=260&h=260"
logo: ilano<b>pat</b>
paginate: 5
paginate_path: "/page:num"
owner:
  name: Patricia Anne Ilano
  email: ilanopatdev@gmail.com
  github:
    show: true
    username: ilanopat
  twitter:
    show: true
    username: ilanopat
  disqus:
    show: true
    username: ilanopat
  linkedin: 
    show: true
    username: ilanopat
permalink: /blog/:title
plugins:
  - jekyll-sitemap

